### ISSUE TITLE
Question about step 1

### ISSUE THREAD

**Issue by R-81** [xuzhengyi1995/Renta_Downloader#1]
How to add my cookies in the program? Which one should i select? Thx

**Comment by R-81** [comment]
i use document.cookie to get the cookies and set variables as README said, but it says HTTPError.

**Comment by R-81** [comment]
auth_key_papy is changed every time i freash index_view, is't right?

**Comment by R-81** [comment]
Sloved, thx.

**Comment by xuzhengyi1995** [comment]
Thank you for your question.
1. For the cookies you can press F12, change to the 'network' and refresh the page to see the cookies send by the request and just copy it to the program,
2. auth_key_papy is changed every time when refresh the page, but I think maybe the last one will also valid by the website.
