### ISSUE TITLE
Script no longer works because Renta has changed its reader

### ISSUE THREAD

**Issue by nutritionalyeest** [xuzhengyi1995/Renta_Downloader#15]
Hi @xuzhengyi1995! It seems like Renta has recently changed how its manga reader looks/behaves, so Renta_Downloader script no longer functions. 
The specific error I get when running the script: 
```Exception: Can not find sum_page on the page```

I was able to create a workaround by setting sum_page by hand. 

I use this script a lot, and I really appreciate it you making it available. :-)

**Comment by vsatyamesc** [comment]
The only problem here is that the Script can no longer calculate the total number of pages. What you can try doing rn is go to line  160 change the code
```
#sum_page = int(re_max_page.findall(data)[0])
sum_page = <Total number of pages of the manga>
```

**Comment by vsatyamesc** [comment]
else, at line 105, replace line re_max_page = re.compile(r'var max_page = parseInt\("(\d+)"\)')
made a pull request

**Comment by vsatyamesc** [comment]
this can be closed now. Issue merged.
