### ISSUE TITLE
Fail to download the manga

### ISSUE THREAD

**Issue by caomeijiangmei** [xuzhengyi1995/Renta_Downloader#18]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\main.py", line 308, in <module>
    start_download(url)
  File "C:\Users\main.py", line 98, in start_download
    download_info = get_download_info(url)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\main.py", line 136, in get_download_info
    raise Exception('Can not find prd_ser on the page')
Exception: Can not find prd_ser on the page

Last week it was working fine when I used it, but since yesterday, I can't download the comics anymore.

**Comment by Micheeeel111** [comment]
same problem

**Comment by nutritionalyeest** [comment]
seems like the viewer code changed very slightly, so it worked again for me when I edited this part of the get_download_info function (lines 103-115)
```

def get_download_info(url):
    is_us = True if url.find('us-dre') != -1 else False
    re_max_page = re.compile(r'max_page=parseInt\("(\d+)"\)')
    if is_us:
        re_base_url = re.compile(r'url_base=\"(.+?)\"')
        manga_base_url = url.split('.com')[0]
    else:
        re_base_url = re.compile(r'url_base2=\"(.+?)\"')
        manga_base_url = ''

    re_cache_update = re.compile(r'cache_update=\"([0-9]+?)\"')
    re_prd_ser = re.compile(r'prd_ser="([0-9]+?)"')
    re_auth_key = re.compile(r'auth_key="(.+?)"')
```

**Comment by caomeijiangmei** [comment]
Tysm~
