### ISSUE TITLE
would you like to make a project for https://bookwalker.jp/

### ISSUE THREAD

**Issue by coremaya** [xuzhengyi1995/Renta_Downloader#2]

**Comment by xuzhengyi1995** [comment]
I have just checked Bookwalker.jp, I think this website is more complicated than renta, I will try my best, but I'm not sure I can make it out.
If I find a way to download it, I will notice you here.
Thank you.

**Comment by coremaya** [comment]
> I have just checked Bookwalker.jp, I think this website is more complicated than renta, I will try my best, but I'm not sure I can make it out.
> If I find a way to download it, I will notice you here.
> Thank you.

thanks，i find a project named bookworm on github ，but i dont know how to use it。 i think you can find something there.

**Comment by xuzhengyi1995** [comment]
> > I have just checked Bookwalker.jp, I think this website is more complicated than renta, I will try my best, but I'm not sure I can make it out.
> > If I find a way to download it, I will notice you here.
> > Thank you.
> 
> thanks，i find a project named bookworm on github ，but i dont know how to use it。 i think you can find something there.

I have checked this website, it's very difficult to get image by using the method in this program, because the js are all extremely uglified, the easier solution is to use the headless browser like selenium and save the canvas. It will be much slower than the method in this program, but it will work.

I'll try to do in this way.
Thank you.

**Comment by zeroaq** [comment]
https://i.postimg.cc/8PF8XDTy/Snipaste-2020-02-08-19-09-46.png

**Comment by zeroaq** [comment]
[url=https://postimages.org/][img]https://i.postimg.cc/8PF8XDTy/Snipaste-2020-02-08-19-09-46.png[/img][/url]

**Comment by zeroaq** [comment]
[url=https://postimages.org/][img]https://i.postimg.cc/8PF8XDTy/Snipaste-2020-02-08-19-09-46.png[/img][/url](url)

**Comment by zeroaq** [comment]
https://postimg.cc/WhPftBFr

**Comment by zeroaq** [comment]
<a href='https://postimg.cc/WhPftBFr' target='_blank'><img src='https://i.postimg.cc/WhPftBFr/Snipaste-2020-02-08-19-09-46.png' border='0' alt='Snipaste-2020-02-08-19-09-46'/></a>

**Comment by zeroaq** [comment]
脚本部分漫画好像下载不了，如果操作有误请指出！

**Comment by xuzhengyi1995** [comment]
> 脚本部分漫画好像下载不了，如果操作有误请指出！

您好，麻烦提供一下该漫画的网址，以方便检查，谢谢。

**Comment by zeroaq** [comment]
> > 脚本部分漫画好像下载不了，如果操作有误请指出！
> 
> 您好，麻烦提供一下该漫画的网址，以方便检查，谢谢。

https://github.com/xuzhengyi1995/Renta_Downloader/issues/2#issuecomment-583727288 这个是目录
tps://dre-viewer.papy.co.jp/sc/view_jsimg2/sample/9-684789-84/FIX001/index.view 这是无法下载的网址

**Comment by zeroaq** [comment]
tps://dre-viewer.papy.co.jp/sc/view_jsimg2/sample/9-684789-84/FIX001/index.view  这是无法下载的网址

https://renta.papy.co.jp/renta/sc/frm/item/155833/title/684789/ 这是目录
好像不止这一漫画无法下载，也有部分不行

**Comment by zeroaq** [comment]
https://dre-viewer.papy.co.jp/sc/view_jsimg2/sample/9-684789-84/FIX001/index.view这是无法下载的网址

https://renta.papy.co.jp/renta/sc/frm/item/155833/title/684789/ 这是目录
好像不止这一漫画无法下载，也有部分不行

**Comment by xuzhengyi1995** [comment]
> [https://dre-viewer.papy.co.jp/sc/view_jsimg2/sample/9-684789-84/FIX001/index.view这是无法下载的网址](https://dre-viewer.papy.co.jp/sc/view_jsimg2/sample/9-684789-84/FIX001/index.view%E8%BF%99%E6%98%AF%E6%97%A0%E6%B3%95%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%BD%91%E5%9D%80)
> 
> https://renta.papy.co.jp/renta/sc/frm/item/155833/title/684789/ 这是目录
> 好像不止这一漫画无法下载，也有部分不行

您好，经检查为构建URL时的疏忽，漏写了一个&符号，已修改，请再次尝试，谢谢！

**Comment by zeroaq** [comment]
请问在哪里下载？

**Comment by xuzhengyi1995** [comment]
> 请问在哪里下载？

您好，如果您有clone目录的话，可以使用git pull直接更新。

或者，您可以到以下链接，
https://github.com/xuzhengyi1995/Renta_Downloader

点击右侧的绿色按钮‘Clone or download'，再点击’Download ZIP'即可下载新的zip包，谢谢。

**Comment by zeroaq** [comment]
好的，谢谢

**Comment by zeroaq** [comment]
好像在Clone or download下载的依旧是久的版本

**Comment by xuzhengyi1995** [comment]
> 好像在Clone or download下载的依旧是久的版本

https://github.com/xuzhengyi1995/Renta_Downloader/archive/master.zip

您可以尝试点击上面的链接直接下载。

或者可以更改一下现有版本的168行，将：
```python
url += "date=" + cache_update
```

更改为:

```python
url += "date=" + cache_update + '&'
```

并且最好将第87行的：
```python
header['Referer'] = 'https://dre-viewer.papy.co.jp/sc/view_jsimg2/9b30e78b669d6dab4b/9-524390-84/FIX001/index.view'
```

更改为:

```python
header['Referer'] = url
```

本次提交只有这两处更改，您可以自由选择更新的方式。

谢谢。

**Comment by zeroaq** [comment]
十分感谢，可以用了

**Comment by coremaya** [comment]
> 十分感谢，可以用了

你买啥漫画了

**Comment by zeroaq** [comment]
就是网址的那漫画

**Comment by xuzhengyi1995** [comment]
> > I have just checked Bookwalker.jp, I think this website is more complicated than renta, I will try my best, but I'm not sure I can make it out.
> > If I find a way to download it, I will notice you here.
> > Thank you.
> 
> thanks，i find a project named bookworm on github ，but i dont know how to use it。 i think you can find something there.

I have finished a version with selenium and tried it, it's a little bit slow but it works [I think], your can find all the info here:

https://github.com/xuzhengyi1995/Bookwalker_Downloader

Thank you.

**Comment by coremaya** [comment]
> > > I have just checked Bookwalker.jp, I think this website is more complicated than renta, I will try my best, but I'm not sure I can make it out.
> > > If I find a way to download it, I will notice you here.
> > > Thank you.
> > 
> > 
> > thanks，i find a project named bookworm on github ，but i dont know how to use it。 i think you can find something there.
> 
> I have finished a version with selenium and tried it, it's a little bit slow but it works [I think], your can find all the info here:
> 
> https://github.com/xuzhengyi1995/Bookwalker_Downloader
> 
> Thank you.

oops,thank a lot.i will try it.
