### ISSUE TITLE
Making it work with ebookrenta (https://www.ebookrenta.com)?

### ISSUE THREAD

**Issue by lickenchittle** [xuzhengyi1995/Renta_Downloader#3]
Is it possible to have it working with ebookrenta (which is basically the english version of renta). They're pretty similar but with slight differences. Thanks.

**Comment by xuzhengyi1995** [comment]
> Is it possible to have it working with ebookrenta (which is basically the english version of renta). They're pretty similar but with slight differences. Thanks.

Yes they are almost the same, I have add the support to the new version and committed it, you can get the new program now.

All the steps are the same, just change the manga URL to the ebookrenta (Like: <http://us-dre4.ebookrenta.com/sc/view_jsimg2_en/3a2d4f07050062a785/9-671847-84/rbc1002/index.view>), and it should work now.

**Comment by xuzhengyi1995** [comment]
And this will not work for the _VertiComix_, The _VertiComix_ use the different viewer and it's just the original images, no need to do anything but just download it.

**Comment by lickenchittle** [comment]
Oh man. You work fast! Thanks a lot!
