### ISSUE TITLE
About the file name

### ISSUE THREAD

**Issue by ker0r0** [xuzhengyi1995/Renta_Downloader#4]
Awesome tool and it works perfectly.
Well, is it possible to change the file name to three digits, such as starting 001 instead of starting 1?

**Comment by xuzhengyi1995** [comment]
Thank you for like the script.
Yes it's possible, I have modified the program, you can just update it or just change the line [302](https://github.com/xuzhengyi1995/Renta_Downloader/blob/5c9130ad755fa995e7dd457bf2f44e817bf9a471/main.py#L302) as follow:

Before:
```python
    with open(imgdir + '/%d.jpg' % page, "wb") as f:
```

After:
```python
    with open(imgdir + '/%03d.jpg' % page, "wb") as f:
```

**Comment by ker0r0** [comment]
Got you. Thank you so much for your quick reply.
