### ISSUE TITLE
I cannot find cookie?

### ISSUE THREAD

**Issue by whiteangel123** [xuzhengyi1995/Renta_Downloader#6]
Hello, I use chrome, and I cannto find Cookie? I found index.view, but I don't know where "cookie" is. Can you show example of what a cookie string looks like?

**Comment by whiteangel123** [comment]
I think I found Cookie. It's a very long string.
But when I inserted it I get "URL error Retry" in the process. Did I insert something wrong

**Comment by whiteangel123** [comment]
Um... this is what I put in...


The process

```
E:\Renta_Downloader-master>python main.py
{'prd_ser': 354164, 'base_url': 'https://dre-aka-p.papy.co.jp/filesv/sc/contents
/354164/6s/0/%d', 'cache_update': None, 'auth_key_papy': 'auth-key=exp=159105681
9~acl=%2Ffilesv%2Fsc%2Fcontents%2F354164%2F6s%2F0%2F%2A~hmac=4b290af0b922d8adde9
ccaaeb7470cc46fed46caf529fc8059bd91b564655b87', 'sum_page': 127, 'is_us': False,
 'manga_base_url': ''}
URLError Retry 1 times
URLError Retry 1 times
URLError Retry 1 times
URLError Retry 1 times
URLError Retry 1 times
URLError Retry 2 times
URLError Retry 2 times
URLError Retry 2 times
URLError Retry 2 times
URLError Retry 2 times
URLError Retry 3 times
URLError Retry 3 times
URLError Retry 3 times
URLError Retry 3 times
URLError Retry 3 times
URLError Retry 4 times
URLError Retry 4 times
URLError Retry 4 times
URLError Retry 4 times
URLError Retry 4 times
```
I don't know why it keeps on error

**Comment by ker0r0** [comment]
Okay, you need `“` after the end of the cookie.

**Comment by whiteangel123** [comment]
Okay I already have " after Cookie. Did I copy the wrong one? :(

`header['Cookie'] = ""`

**Comment by ker0r0** [comment]
Well, your cookie is fine for now, but I found out other error in your code. 
You have to change from `"` to `'` for the URL of the manga.

```
# URL of the manga
url = 'https://dre-viewer.papy.co.jp/sc/view_jsimg2/cbd63773fe531f9ec7/9-493852-84/FIX001/index.view'
```

Your code looks like below;
 ```
# URL of the manga
url = "https://dre-viewer.papy.co.jp/sc/view_jsimg2/cbd63773fe531f9ec7/9-493852-84/FIX001/index.view"
```

**Comment by xuzhengyi1995** [comment]
Thank you so much @ker0r0 for helping me respond the question !

First @whiteangel123 , **be careful about your cookies !  Do not put this to public like this, I will suggest you delete your Cookies from this issue for your account safety. This is very important!**

I am sorry but I have tested the script just now and it works fine for me.
I think maybe it's the problem of your cookies.
Compare to my cookies, your cookies miss some attributes.

My cookies have:
```
rct
BID
adlt_code
adlt_disp
_gcl_au
exauth_tw
chk
rbc
bCode
l_login
papy_ret
renta_ser
allow_adlt
BVAR
uriagePage
renta_period
mds
USC1
uattr
RFP
r_item_ab
uc_wh
```

Yours:
```
rct
BID
BVAR
allow_adlt
adlt_code
adlt_disp
uattr
RFP
r_item_ab
_gcl_au
_ga
_gid
__lt__cid.fa7456cd
__lt__sid.fa7456cd
_fbp
USC1
rbc
bCode
renta_ser
pay
uc_wh
renta_period
mds
```
Please make sure that you are getting the cookies like the image below:


![image](https://user-images.githubusercontent.com/29002064/83528449-afc75e00-a51b-11ea-978a-104978463f43.png)

Thank you!

**Comment by whiteangel123** [comment]
Oops!!
Hmmm, that's weird, I already copy from the same place.

`rct
BID; 
allow_adlt; 
adlt_code; 
adlt_disp; 
_gcl_au;
 _ga; 
__lt__cid; 
r_item_ab; 
renta_ser; 
_gid; 
rbc=1; 
bCode=0; 
pay=0; 
uriagePage; 
_fbp; 
ic_r; 
renta_period=0; 
BVAR; 
RFP; 
uattr; 
uc_wh; 
__lt__sid; 
USC1; 
mds
`

Maybe it's because the website is actually blocked in my country. I have to use VPN to open Renta Papy, maybe that's what making it error. When I tried to download from the English website, Ebookrenta, it downloads successfully.

**Comment by xuzhengyi1995** [comment]
Yes maybe this is the problem, you can try to use the vpn and see if it works or not, thank you!

**Comment by whiteangel123** [comment]
@xuzhengyi1995 After using VPN, the manga downloaded successfully. Thank you!

**Comment by xuzhengyi1995** [comment]
You are welcome :)
